Repository silverstripe/silverstripe-staticpublishqueue, pull requests merged in 2019-04, with the labels that each got.

#99 typo in ".htacces example"
  docs/en/advanced_configuration.md
Labels: affects/v4, type/docs

#95 Add DB index on URLSegment
  .travis.yml
  code/model/StaticPagesQueue.php
Labels: affects/v3, change/minor

#96 Ensure URLs get queued when BASE_URL is set
  code/model/URLArrayObject.php
Labels: affects/v4, change/patch

#69 Fix crash in collectChanges
  code/extensions/engines/SiteTreePublishingEngine.php
Labels: affects/v3, change/patch
